config/routes.rb
Rails.application.routes.draw do


  get 'geocoder/findaddress'
  root 'pages#index'
  get 'backoffices/users'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks:  'users/omniauth_callbacks'
  }
  
  
  resources :backoffices
  resources :users
  resources :shops do 
    member do
      post 'add_tag'
      delete 'remove_tag/:tag_id', to: 'shops#remove_tag', as: 'remove_tag'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
    enum state:[:draft, :published, :hidden]
    scope :published, -> { where(state: 1) }
    has_many :shop_tags ,  dependent: :destroy
    has_many :tags, through: :shop_tags
    #has_one_attached :photo
    accepts_nested_attributes_for :tags

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  #before_action :edit_my_shop, only: [:edit]
  #before_action :delete_shop, only: [:destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  skip_authorization_check :only => [:index, :show]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all.published

    @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow "<h5>" + shop.name + "</h5>" + "<p>" + shop.description + "</p>" 
      #"<span class='badge badge-info'>" +   shop.tags[0].name + "</span>"
      #marker.infowindow shop.description 
      #marker.infowindow shop.tags
    end    
    @my_shops = []
      @shops.each do |shop|
      if shop.user_id == current_user .id
        @my_shops << shop
      end
    end
    @shops = if params[:q].present?
       Shop.joins(:tags).where("shops.name ilike ? OR tags.name ilike ?", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      Shop.all.published  
    end

  end
  # GET /shops/1
  # GET /shops/1.json
  def show

    render layout: "shop-edit"
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    render layout: "shop-edit"
  end

  # GET /shops/1/edit
  def edit
    
    # si tienda.user == current_user
    render layout: "shop-edit"

  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id
    #tags = params[:tags].split(',')
    #tags.each do |tag|
      #@shop.tags << Tag.new(name:tag) 
    #end
    #@shop.address = Geocoder.coordinates(params[:address])
    respond_to do |format|
      if @shop.save
        format.html { redirect_to shops_path, alert: 'La tienda se a enviado para su aprobación' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
 

  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to backoffices_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_tag
    @shop.tags << Tag.new(name: params[:name]) 
    redirect_to backoffices_url
  end

  def remove_tag
    tag = Tag.find(params[:tag_id])
    @shop.tags.delete(tag)
    redirect_to backoffices_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(
        :longitude, :latitude, :name, :description, :state, :address, 
        #tags_attributes:[:name, :id]
        )    
      end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_all-shops.html.erb
<div class="owl-carousel owl-theme card-deck">
 <% @shops.each do |shop| %>
  <div class="item card">
    <div class="card-body">
      <h5><%= shop.name %></h5>
      <p class="card-description"><%= shop.description %></p>
      <p class="card-address"><%= shop.address %></p>
      <div class="tags-group">
        <% shop.tags.each do |tag| %>
            <span class="badge badge-info" > <%= tag.name %> </span>
        <% end %>  
      </div>

    </div>
     <% if current_user.role == 'admin' %>
      <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Latitud: </strong><%= shop.latitude%></li>
          <li class="list-group-item"><strong>Longitud: </strong><%= shop.longitude%></li>
        </ul>
    <% end %>
     <% if current_user.role == 'admin' %>
    <div class="card-footer">
          <span><%= link_to 'Show', shop %></span> |
          <span><%= link_to 'Edit', edit_shop_path(shop) %></span>        
    </div>
     <% end %>
  </div>
  <% end %>
</div>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

     
      <% shop.errors.full_messages.each do |message| %>
        <div class="alert alert-error"><%= message %></div>
      <% end %>
    
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:'form-control' %>
  </div>
  <% if current_user.role == "admin" %>
    <div class="form-group">
      <%= form.label :state %>
      <%= form.select :state, options_for_select([["Draft", :draft],["Publicado",:published],["Escondido",:hidden]], params[:state] ) , class:'form-control' %>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address , class:'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/shops/_my-shops.html.erb
<div class="table-section">
  <div class="container-fluid">

<table class="table-striped table">
  <thead>
    <tr>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Name</th>
      <th>Photo</th>
      <th>Description</th>
      <th>Satate</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_shops.each do |shop| %>
      <tr>
        <td><%= shop.longitude %></td>
        <td><%= shop.latitude %></td>
        <td><%= shop.name %></td>
        <td>
        <% shop.tags.each do |tag|%>
          <%= tag.name %>
        <% end %>   
        <%= form_tag(add_tag_shop_path(shop.id)) do %>
            <%= text_field_tag 'name' %>
        <% end %>
        </td>
        <td><%= shop.description %></td>
        <td><%= shop.state %></td>
        <td><%= shop.address %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><% link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/shops/_sidepanel.html.erb
<div id="sidepanel">
    <div class="sidepanel-header">
        <button id="esconder" class="btn"><i class="fa fa-align-left" aria-hidden="true"></i></button>
        <img src="<%= asset_path('logo-1.png') %>" alt="logo" width="150">
    </div>
    <div class="panel-section">
        <form action="<%= shops_path %>" method="get" class="my-3">
        <div class="form-group">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Buscar"  name="q">
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit">Buscar</button>
                </div>
            </div>
        </div>
        </form>
    </div>
    <div class="panel-section">
        <div class="box">
            <div class="form-wrap">
            <%= form_with(model: @shop , local: true, scope: "shop") do |form| %>
             <% if current_user.role == 'admin'  %>
                <div class="form-group ">
                    <%= form.label :longitude %>
                    <%= form.text_field :longitude ,class:'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :latitude %>
                    <%= form.text_field :latitude ,class:'form-control' %>
                </div>
            <% else %>
                <div class="form-group ">
                    <%= form.hidden_field :longitude  %>
                </div>
                <div class="form-group">
                    <%= form.hidden_field :latitude %>
                </div>
            <% end %>



            <div class="form-group">
                <%= form.label :name, 'Nombre de la tienda' %>
                <%= form.text_field :name ,class:'form-control' %>
            </div>


            <div class="form-group">
                <%= form.label :description, 'Descripción' %>
                <%= form.text_area :description ,class:'form-control' %>
                <small>Agrega #hashtags para mejorar la clasificación de la tienda!</small>
            </div>
            <% if current_user.role == "admin" %>
                <div class="form-group">
                <%= form.label :state %>
                <%= form.select :state, options_for_select([["Draft", :draft],["Publicado",:published],["Escondido",:hidden]], params[:state] ) %>
                </div>
            <% end %>
            
            <div class="form-group">
                <%= form.label :address, 'Dirección' %>
                <%= form.text_field :address ,class:'form-control' %>
            </div>
            
            <%# render 'tags' %>
        
            <div class="form-group">
                <%= form.submit 'Nueva tienda' , class:'btn btn-primary' %>
                <%# link_to 'New Shop', new_shop_path %>
            </div>
            <% end %>
            </div>
            </div>

    </div>
</div>

app/views/shops/_tags.html.erb
<div class="form-group">
<%= form.fields_for :tags_attributes do |f|  %>
    <%= f.label :name, 'Etiquetas' %>
    <%= f.text_field :name ,class:'form-control' %>
    <span class="small-text">Separar etiquetas por comas</span>
<% end %>
</div>

app/views/shops/edit.html.erb
<h3>Editar tienda</h3>
<div class="row">
<div class="col-md-4">
<div class="card">
    <div class="card-body">
    <%= render 'form', shop: @shop %>
    </div>
    </div>
</div>
</div>
<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<%= render 'sidepanel' %>
<div class="page-shop mt-4-rem">

  <% if notice %>

    <div class="alert alert-warning alert-dismissible fade show" role="alert" id="shopAlert">
     <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if alert %>

    <div class="alert alert-info alert-dismissible fade show" role="alert" id="shopAlert">
     <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>


  <div style='width: 100wv;'>
    <div id="map"></div>
  </div>
  <div class="container-fluid">
    <div class="btn-section d-flex justify-content-between">
      <h3 class="my-3">Todas las tiendas</h3>
      <input type="button" value="recargar posición" id="reload" class="btn btn-primary my-3">

    </div>
    <div class="carrousel-container">
      
      <%= render 'all-shops' %>
    </div>
  </div>




    

  <div id="tiendas">

  </div>


</div>
<script>


$(document).on('turbolinks:load', function () {
$('#reload').click(function() {
    location.reload();
});


var input = document.getElementById('shop_address');
var autocomplete = new google.maps.places.Autocomplete(input);

// Crea el Marcador de la posición actual
function displayOnMap(position){
  var Marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    picture: {
        url: "<%= asset_path('icon-mini.png') %>",
        width:  36,
        height: 36
    },
  });
  handler.map.centerOn(Marker);
  console.log('More or less ' + position.coords.accuracy + ' meters.');
  console.log(Marker)
};
    

// Crea el Mapa de google
handler = Gmaps.build('Google');
//currentPosition();
handler.buildMap({
    disableDefaultUI: true,
    provider: {
      center: new google.maps.LatLng({lat: -33, lng: -70}),
      zoom: 15
    },
    internal: {
      id: 'map'
    }
    
},
  function(){
    
    // llama la función que crea la posición actual
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(displayOnMap)
    }
    // Crea las tiendas guradadas en la base de datos
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    // Al hacer click genera una tienda nueva
    google.maps.event.addListener(handler.getMap(), "click", function(event){  
        var latitude = event.latLng.lat();
        var longitude = event.latLng.lng();      
        console.log(latitude, longitude);
        // Añade las coordenadas al formulario
        $('#shop_longitude').val(longitude);
        $('#shop_latitude').val(latitude);
        var latitudLongitud = {lat: latitude, lng:longitude};
        // llama a la creción del marcador de tienda
        addMarker(event.latLng);
        // Crea la dirección en humano
        var geocoder = new google.maps.Geocoder;
        geocoder.geocode({'location': latitudLongitud}, function(results, status) {
          if (status === 'OK') {
            if (results[0]) {
              $('#shop_address').val(results[0].formatted_address);
              console.log('aqui'+ latitudLongitud.lat + latitudLongitud.lng );
            } else {
              window.alert('No results found');
            }
          } else {
            window.alert('Geocoder failed due to: ' + status);
          }
        });
    });
    $('#shop_address').focusout(function(){
      // Crea la direccion en latitud y long
            var geocoder2 = new google.maps.Geocoder();
            var address = document.getElementById('shop_address').value;
            geocoder2.geocode({'address': address}, function(results, status) {
              if (status === 'OK') {
                handler.getMap().setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                  map: handler.getMap(),
                  position: results[0].geometry.location
                });
              } else {
                alert('Geocode was not successful for the following reason: ' + status);
              }
              lat_address = results[0].geometry.location.lat()
              lng_address = results[0].geometry.location.lng()
              $('#shop_longitude').val(lng_address);
              $('#shop_latitude').val(lat_address);
            });


      });
    

  }
);


// Este código permite marcar solo un punto.

var userMarker;
function addMarker(location) {
  if (userMarker) {
    userMarker.setPosition(location);
  } else {
    userMarker = new google.maps.Marker({
      position: location,
      map: handler.getMap()
    });
  }

}


});


  $('[name="q"]').keyup(function (e) { 
    $.ajax({
      type: "get",
      url: "<%= shops_url %>",
      data: {q : $(this).val()},
      dataType: "json",
      success: function (response) {
        
      }
    });
    console.log()
});

</script>

app/views/shops/index.js.erb
$('#tiendas').html("<%= j render @shops %>");

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-4">

<div class="card">
<div class="card-body">
<p>
  <strong>Longitude:</strong>
  <%= @shop.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @shop.latitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>


<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @shop.state %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>


</div>

</div>
</div>
</div>