config/routes.rb
Rails.application.routes.draw do


  get 'geocoder/findaddress'
  root 'pages#index'
  get 'backoffices/users'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks:  'users/omniauth_callbacks'
  }
  
  
  resources :backoffices
  resources :users
  resources :shops do 
    member do
      post 'add_tag'
      delete 'remove_tag/:tag_id', to: 'shops#remove_tag', as: 'remove_tag'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffices_controller.rb
class BackofficesController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource :class => false
  
  def index
    @shops = Shop.all
  end
  def users 
    @users = User.all
  end
  def tags
    @tags = Tags.all
  end
  def remove_tag
    tag = Tag.find(params[:tag_id])
    @shop.tags.delete(tag)
    redirect_to backoffices_path
  end


end

app/helpers/backoffices_helper.rb
module BackofficesHelper
end

app/views/backoffices/_charts.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = {"ejemplo1": 20, "ejemplo2": 30} %>
<%= bar_chart my_chart %>

app/views/backoffices/index.html.erb
<table class="table table-striped my-3" id="shopsTable" style="margin-top:40px">
<thead>
    <tr>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Name</th>
      <th>Description</th>
      <th>Satate</th>
      <th>Address</th>
      <th>Tags</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
</thead>
<tbody>

 <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.longitude %></td>
        <td><%= shop.latitude %></td>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td><%= shop.state %></td>
        <td><%= shop.address %></td>
       
          <td>
        <% shop.tags.each do |tag| %>
          <a href="<%= remove_tag_shop_path(shop, tag)  %>"class="badge badge-info" data-method="delete"> <%= tag.name %> <span class="badge badge-light">x</span></a>
        <% end %>   
        <%= form_tag(add_tag_shop_path(shop.id)) do %>
            <%= text_field_tag 'name' , '',class:'form-control' %>
        <% end %>      
        </td>

        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/backoffices/users.html.erb
<table class="table table-striped" id="UsersTable">
<thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Apllido</th>
      <th>Email</th>
      <th>role</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th> 
      
    </tr>
</thead>
<tbody>

 <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Editar', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Borrar', user ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
</table>