config/routes.rb
Rails.application.routes.draw do


  get 'geocoder/findaddress'
  root 'pages#index'
  get 'backoffices/users'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks:  'users/omniauth_callbacks'
  }
  
  
  resources :backoffices
  resources :users
  resources :shops do 
    member do
      post 'add_tag'
      delete 'remove_tag/:tag_id', to: 'shops#remove_tag', as: 'remove_tag'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav-backoffice.html.erb
<nav  id="navigation" class="navbar navbar-expand-lg bg-dark nav-backoffice">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="<%= asset_path('logo-blanco.png') %>" alt="logo" class="nav-brand">
  </a>

  <button class="navbar-toggler-icon navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Navegación">

    <span></span>
    <span></span>
    <span></span>

  </button>


  <div class="collapse navbar-collapse" id="navbarMain">
    <ul class="navbar-nav">
      <% if !user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Registrarse</a>
        </li>

      <% end %>
       <li class="nav-item">
          <a class="nav-link" href="<%= backoffices_path %>">Tiendas</a>
        </li>
       <li class="nav-item">
          <a class="nav-link" href="<%= backoffices_users_path %>">Usuarios</a>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item d-flex justify-content-start">
          <%# if current_user.avatar.attached? %>
              <%# image_tag current_user.sized(:avatar) | current_user.avatar   %>
              <div class="avatar"><%# image_tag current_user.sized(:avatar) %></div> 
          <%# end %>
            <span><%= current_user.name %> (<%= current_user.role %>)</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= shops_path %>"> Ver app</a>
        </li>
       <li class="nav-item">
        <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
       </li>
      <% if current_user.role == "admin" %>
        <li class="nav-item"><%= link_to 'Backoffice', backoffices_path, class:'nav-link' %></li>
      <% end %>
      
      <% end %>
    
    </ul>
     <%# aca va el otro menu %>

  </div>
</nav>

app/views/layouts/_nav-page.html.erb
<nav  id="navigation" class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="<%= asset_path('logo-1.png') %>" alt="logo" class="nav-brand">
  </a>
  <button class="navbar-toggler-icon navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Navegación">

    <span></span>
    <span></span>
    <span></span>

  </button>


  <div class="collapse navbar-collapse" id="navbarMain">
    <ul class="navbar-nav">
      <% if !user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Registrarse</a>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item d-flex justify-content-start">
          <%# if current_user.avatar.attached? %>
              <%# image_tag current_user.sized(:avatar) | current_user.avatar   %>
              <div class="avatar"><%# image_tag current_user.sized(:avatar) %></div> 
          <%# end %>
            <span><%= current_user.name %> (<%= current_user.role %>)</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= shops_path %>"> Ver app</a>
        </li>
       <li class="nav-item">
        <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
       </li>
      <% if current_user.role == "admin" %>
        <li class="nav-item"><%= link_to 'Backoffice', backoffices_path, class:'nav-link' %></li>
      <% end %>
      
      <% end %>
    
    </ul>
     <%# aca va el otro menu %>

  </div>
</nav>

app/views/layouts/_nav-shop.html.erb
<nav  id="navigation" class="navbar navbar-expand-lg">
  <button id="mostrar" class="btn"><i class="fa fa-align-left" aria-hidden="true"></i></button>

  <a class="navbar-brand" href="<%= root_path %>">
    <img src="<%= asset_path('logo-1.png') %>" alt="logo" class="nav-brand">
  </a>
  <% if user_signed_in? %>
  <% end %>
  <button class="navbar-toggler-icon navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Navegación">

    <span></span>
    <span></span>
    <span></span>

  </button>


  <div class="collapse navbar-collapse" id="navbarMain">
    <ul class="navbar-nav">
      <% if !user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Registrarse</a>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item d-flex justify-content-start">
          <a href="<%= edit_user_registration_path(current_user.id) %>"><span><%= current_user.name %> (<%= current_user.role %>)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= shops_path %>"> Ver app</a>
        </li>
       <li class="nav-item">
        <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
       </li>
      <% if current_user.role == "admin" %>
        <li class="nav-item"><%= link_to 'Backoffice', backoffices_path, class:'nav-link' %></li>
      <% end %>
      
      <% end %>
    
    </ul>
     <%# aca va el otro menu %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Healthyshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCSQscXqUOBCQ89ftN6aknUwhoBbp1unCo" data-turbolinks-track="reload" ></script>
    <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyCSQscXqUOBCQ89ftN6aknUwhoBbp1unCo&libraries=places" type="text/javascript" data-turbolinks-track="reload" ></script>

    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" ></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>
  <body>
  
    <%= render 'layouts/nav-shop' %>
  
        <%= yield %>
  
  

  </body>
</html>

app/views/layouts/backoffices.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Healthyshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%# <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" >
     <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" data-turbolinks-track="reload" ></script>  %>

  </head>
  <body>
  
    <%= render 'layouts/nav-backoffice' %>
    <div class="page-backoffice mt-4-rem">
    <div class="container-fluid">
    <%= yield %>
    
    </div>
    </div>
    
  <script>

</script>

  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Healthyshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <!-- only if you need custom infoboxes -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>
  <body>
  
    <%= render 'layouts/nav-page' %>
  
    <%= yield %>
    

  </body>
</html>

app/views/layouts/shop-edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop edit Healthyshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <!-- only if you need custom infoboxes -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>
  <body>
  
    <%= render 'layouts/nav-page' %>
    
    <div class="page-shop-edit mt-4-rem">
        <div class="container">
            <%= yield %>
        
        </div>
    </div>
    

  </body>
</html>